# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78857ff319fbe60a76b1209f72dafa68876ab2cb2037de81214afa5c2ce03f28bf7bfb031a34b5290866cece05c7661f0c27be90cbbd8e562b79aef85642c610

test:
  secret_key_base: c1f7910496b3581928876ab02ce5627944d89e808cedb366524c6f878d74592aa11d94f669637df834372faa97c8305a15505d0a53cc437ea1df89f63f9aeff5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
